---
name: "📚 Documentation issue report"
about: "Report an issue in the project's documentation or README.md file."
title: "[Doc]: "
labels: "Documentation"
assignees: jaflesch

body:
  - type: markdown
    attributes:
      value: |
        **Thanks :heart: for taking the time to fill out this feature request report!**
        
        We kindly ask that you search to see if an issue [already exists](https://github.com/jaflesch/playground-ci/issues?q=is%3Aissue+sort%3Acreated-desc+) before submitting a new one.

        We are also happy to accept contributions from our users. For more details see [here](https://github.com/jaflesch/playground-ci/blob/master/CONTRIBUTING.md).

        Please read our Rules of Conduct at this repository's `.github/CODE_OF_CONDUCT.md`
  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce the error
      description: |
        Write the steps here (add or remove as many steps as needed)
      placeholder: |
        1. Use x argument / navigate to
        2. Fill this information
        3. Go to...
        4. See error -->
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context or additional information about the problem here
    validations:
      required: false

