name: Deploy Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'Deployment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Clean Install
        run: npm ci
      - name: Unit Test
        run: npm test

