name: Synchronize Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  build:
    name: 'Labels'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/labels.yml
      - uses: EndBug/label-sync@v2.3.3
        with:
          config-file: .github/labels.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-other-labels: false
          #dry-run: true
